services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo_db
    volumes:
      - pgdata_todos:/var/lib/postgresql/data
    networks:
      - internal
#    ports:
#      - "127.0.0.1:5555:5432"

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    restart: always
#    ports:
#      - "127.0.0.1:15672:15672"
#      - "127.0.0.1:5672:5672"
    environment:
      - RABBITMQ_MANAGEMENT_BIND_IP=0.0.0.0
      - RABBITMQ_MANAGEMENT_PORT_NUMBER=15672
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
      - RABBITMQ_USERNAME=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
    networks:
      - internal

  api-gateway:
    build:
      context: ./api-gateway
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - internal
    restart: always

  todo-processor:
    build:
      context: ./todo-processor
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - internal
    restart: always

volumes:
  pgdata_todos:

networks:
  internal:
    driver: bridge
